#!/bin/bash

set -euo pipefail
. /.functions

#
# Init all the SSL-related stuff
#
init_ssl

set_or_default JAVA_OPTS
set_or_default JAVA_OPTS_CONTAINER_FLAGS
exec java ${JAVA_OPTS} ${JAVA_OPTS_CONTAINER_FLAGS} \
	-Dserver.ssl.enabled=true \
	-Dserver.ssl.key-alias="${JAVA_KEY_ALIAS}" \
	-Dserver.ssl.key-store="${JAVA_KEYSTORE}" \
	-Dserver.ssl.key-store-password="${JAVA_KEYSTORE_PASSWORD}" \
	-Dserver.ssl.key-store-type="${JAVA_KEYSTORE_TYPE}" \
	-jar "/usr/bin/alfresco-transform-core-aio.jar"
