#!/bin/bash

set -euo pipefail

# Init SSL
[ -v SSL_DIR ] || SSL_DIR="/.ssl"
/usr/local/bin/acme-init

[ -v JAVA_OPTS ] || JAVA_OPTS=""
exec java \
	-Dserver.ssl.enabled=true \
	-Dserver.ssl.key-alias=acme \
	-Dserver.ssl.key-store="${SSL_DIR}/keystore.pkcs12" \
	-Dserver.ssl.key-store-password=$(<"${SSL_DIR}/keystore.pass") \
	-Dserver.ssl.key-store-type=PKCS12 \
	${JAVA_OPTS} -jar "/usr/bin/alfresco-transform-core-aio.jar"
