#!/bin/bash

set -euo pipefail
. /.functions

# Init SSL
init_ssl

set_or_default JAVA_OPTS ""
exec java \
	-Dserver.ssl.enabled=true \
	-Dserver.ssl.key-alias=acme \
	-Dserver.ssl.key-store="${SSL_DIR}/keystore.pkcs12" \
	-Dserver.ssl.key-store-password=$(<"${SSL_DIR}/keystore.pass") \
	-Dserver.ssl.key-store-type=PKCS12 \
	${JAVA_OPTS} -jar "/usr/bin/alfresco-transform-core-aio.jar"
